trigger:
  - main

pool:
  vmImage: ubuntu-22.04
  name: Azure Pipelines

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run lint
    displayName: 'npm install and lint'

  - task: Docker@2
    condition: and (succeeded(), eq(variables['task.NodeTool@0.status'], 'success'))
    inputs:
      containerRegistry: 'docker-hub-connection'
      repository: 'vetplus-api'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'