trigger:
  - main

pool:
  vmImage: ubuntu-22.04
  name: Azure Pipelines

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run lint
      npm run build
    displayName: 'npm install, lint and build'

  - task: Docker@2
    inputs:
      containerRegistry: 'docker-hub-connection'
      repository: 'vetplus-api'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'