trigger:
  - main
  - dev

pool:
  vmImage: ubuntu-22.04

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run lint
      npm run build
    displayName: 'npm install, lint and build'

  - task: Docker@2
    inputs:
      containerRegistry: 'docker-hub-connection'
      repository: 'chrissst/vetplus-api'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'alpha'
    displayName: 'Build and Push Docker image'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export NETLIFY_AUTH_TOKEN="$(NETLIFY_AUTH_TOKEN)"
        netlify login
        npm run docs:generate
        ls
        netlify deploy --dir=docs --prod
    displayName: 'Deploy to netlify'
    timeoutInMinutes: 5
