FROM node:20.5-alpine3.18

ARG DATABASE_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG AWS_S3_ACCESS_KEY_ID
ARG AWS_S3_SECRET_ACCESS_KEY
ARG AWS_S3_BUCKET_NAME
ARG AWS_S3_REGION

ENV NODE_ENV=production
ENV DATABASE_URL=$DATABASE_URL_QA
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV AWS_S3_ACCESS_KEY_ID=$AWS_S3_ACCESS_KEY_ID
ENV AWS_S3_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY
ENV AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME
ENV AWS_S3_REGION=$AWS_S3_REGION

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install --production --silent && mv node_modules ../

COPY . .

RUN npm run build

EXPOSE 3000

RUN chown -R node /usr/src/app

USER node

CMD ["npm", "run", "start:prod"]
