export enum CreateUserResult {
  EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST',
  PASSWORD_WEAK = 'PASSWORD_WEAK',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
}
